### ISSUE TITLE
Add option to set lower fees

### ISSUE THREAD

**Issue by nybe** [blockfirm/bithodl-app#2] opened 2018-02-08 22:53 UTC
Trying to move a small (was a test) amount out of a wallet now but says not enough for fee (are they adjustable?) how can I figure out the public address so o can send more money in?

**Comment by ghost** [comment] 2018-02-08 22:59
Your issue doesn't follow our guidelines. Please fix the following:

* Issue must have at least one label [(?)](https://gitmagic.io/rules/#/issue/label-must-be-set)
* Issue title must be in imperative, present tense \(e\.g\. "add", "fix", "change"\) [(?)](https://gitmagic.io/rules/#/issue/subject-must-be-in-tense)

[Click here](https://app.gitmagic.io/blockfirm/bithodl-app/2/c240cf46-60db-4e53-b957-91ef15bd4a78/2d68b592-06c9-4047-b6d7-1471a11356a8) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>

**Comment by nybe** [comment] 2018-02-08 23:29
Huh? Just tell me how to get the public key to my now unlocked wallet so I can Awn more money to it?

//Bob

**Comment by timothyej** [comment] 2018-02-09 19:29
Hi,

It's not possible to add more funds to the same address. And if the current amount is smaller than the fees, it wouldn't make sense to transfer more money into it because they would still be consumed by the fees and you would even have to pay for the extra transaction.

However, the fees are estimated by the Bitcoin Core client and are rather high. A better solution would be for me to enable setting a lower fee. But that would only work if the amount you're trying to send is still below that lower fee.

May I ask how much you want to send? You can email me at <timothy@blockfirm.se> if you don't want to disclose the amount here.

Thank you,
Timothy

**Comment by nybe** [comment] 2018-02-09 19:42
So does that mean I can’t continue to add to wallets that I’ve already created? that kinda sucks

**Comment by timothyej** [comment] 2018-02-09 20:11
You'd have to create a new address with BitHodl. It can have the same date as the precious one but it would show as a separate item inside the app. In the future I might add the functionality to "refill" already existing addresses.

**Comment by nybe** [comment] 2018-02-09 20:14
What if I were to make note of the address of a newly created wallet and then continue to send to it later on? Would that work or would the money be lost due to the lock on an existing wallet?

**Comment by timothyej** [comment] 2018-02-09 20:21
The wallet would handle it by displaying two items in the list that are locked until the same date. They wouldn't be lost but they would be locked to the same date as the address was created for.

The address shown when transferring money to BitHodl is specially generated to lock everything being sent to it until the specified date. Making multiple transactions to it would just result in more items in the BitHodl app, each showing the amount of each transaction.

**Comment by ghost** [comment] 2018-02-11 19:16
Thank you, everything looks good now! :bowtie:

**Comment by timothyej** [comment] 2018-02-12 18:13
This issue has been fixed in the latest release of BitHodl, version 1.1.0. Please note that it can take some time before the update is available on the App Store.

Once updated, try setting a lower fee under *Settings* -> *Transaction fees*. But keep in mind that setting a too low fee could cause your transaction to be unconfirmed for a long time. Email me at <timothy@blockfirm.se> if you need any help.

Thank you for contributing to BitHodl.

**Closed as completed by timothyej** 2018-02-12 18:13 UTC
Labels: feature, released

**Comment by nybe** [comment] 2018-02-12 18:24
Very cool, I’ll try it out when available 

//Bob
